### ISSUE TITLE
include in Enide Studio

### ISSUE THREAD

**Issue by paulvi** [culmat/eExplorer#24]
I would like to include eExplorer into Nodeclipse updated and Enide Studio   http://www.nodeclipse.org/enide/studio/2014/  

However because only win32 version exists, I can't add it to update site configuration, etc

```
<?xml version="1.0" encoding="UTF-8"?>
<site>
   <feature url="features/com.github.culmat.eexplorer.feature_1.0.0.qualifier.jar" id="com.github.culmat.eexplorer.feature" version="1.0.0.qualifier" os="win32"/>
</site>
```

Are you OK with that? Any requirements, comments?

Could you please make it not only win32 (and check on plugin initialization)

**Comment by culmat** [comment]
Closing this, see #31
